language: php

sudo: true

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

sudo: false

matrix:
  fast_finish: true

  allow_failures:
    - php: hhvm

cache:
  directories:
    - laravel

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --prefer-dist --no-interaction

script:
  - cd laravel
  - composer update
  - php artisan vendor:publish --force
  - php artisan migrate --seed
  - phpunit "vendor/$PACKAGE_NAME"

  # run the script calling unit tests and so on